RealMission7/Controllers/PayController.cs
using Microsoft.AspNetCore.Mvc;
using RealMission7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RealMission7.Controllers
{
    public class PayController : Controller
    {
        private IPayRepository repo { get; set; }
        private Cart cart { get; set; }

        public PayController (IPayRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Pay());
        }

        [HttpPost]
        public IActionResult Checkout(Pay payment)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty.");
            }

            if (ModelState.IsValid)
            {
                payment.Lines = cart.Items.ToArray();
                repo.SavePayment(payment);
                cart.ClearCart();

                return RedirectToPage("/CheckoutCompleted");
            }

            else
            {
                return View();
            }
        }
    }
}

RealMission7/Pages/Buy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RealMission7.Infrastructure;
using RealMission7.Models;

namespace RealMission7.Pages
{
    public class BuyModel : PageModel
    {

        private iBookRepository repo { get; set; }

        public BuyModel (iBookRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }

        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            cart.AddItem(b, 1);

            return RedirectToPage(new {  ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }
    }
}

RealMission7/Pages/CheckoutCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RealMission7.Pages
{
    public class CheckoutCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RealMission7/Pages/Buy.cshtml
@page
@model RealMission7.Pages.BuyModel
@{
}

<h2>Your Cart</h2>

<table class="table table-bordered table-hover">

    <thead>
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.cart.Items)
        {
        <tr>
            <td>@i.Book.Title</td>
            <td>@i.Quantity</td>
            <td>@i.Book.Price</td>
            <td>@(i.Quantity * i.Book.Price)</td>

            <td class="text-center">
                <form method="post" asp-page-handler="Remove">
                    <input type="hidden" name="BookId" value="@i.Book.BookId" />
                    <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                    <button type="submit" class="btn-sm btn-danger">Remove</button>
                </form>
            </td>
        </tr>

        }
    </tbody>

    <tfoot>
        <tr>
            <td clospan="3">Total:</td>
            <td>@Model.cart.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Pay">Checkout</a>
</div>

RealMission7/Pages/CheckoutCompleted.cshtml
@page
@model RealMission7.Pages.CheckoutCompletedModel
@{
}

<div class="text-center text-uppercase text-xl-center">
    <h2>Thanks! These Books will change your life </h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

RealMission7/Pages/_BuyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        The Best Book Store Ever
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>