RealMission7/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RealMission7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RealMission7.Components
{
    public class CartSummaryViewComponent : ViewComponent 
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

RealMission7/Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RealMission7.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RealMission7.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private iBookRepository repo { get; set; }

        public CategoryViewComponent (iBookRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["Category"];

            var category = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(category);
        }
    }
}

RealMission7/Views/Shared/BookSummary.cshtml
@{
}
@model Book

<div class="card card-outline-primary m-1 p-1 bg-light">
    <div class="bg-light p-1">
        <h3>
            @Model.Title
            <span class="badge badge-pill badge-warning" style="float:right">
                <small>Price: @Model.Price</small>
            </span>
        </h3>
    </div>


    <div class="card-text p-1 border-top">Written By: @Model.Author</div>
    <div class="card-text p-1 border-top">Published By: @Model.Publisher</div>
    <div class="card-text p-1 border-top">ISBN: @Model.Isbn</div>
    <div class="card-text p-1 border-top">Classification: @Model.Classification</div>
    <div class="card-text p-1 border-top">Category: @Model.Category</div>
    <div class="card-text p-1 border-top border-bottom">Number of Pages: @Model.PageCount</div>

    <form method="post" asp-page="/Buy">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />


        <span class="card-text">
            <button type="submit" class="btn btn-success btn-small float-right">Buy</button>
        </span>
    </form>
</div>

RealMission7/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RealMission7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">The I.S. Book Store</div>
                <div class="col-6 text-right">
                    <vc:cart-summary></vc:cart-summary>
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">
        <div id="category" class="col-3 text-left">
            <vc:category></vc:category>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>